# Stores the core application data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
  namespace: mydomain-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi
---
# Workspace for file operations in the workflows
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-local-files-pvc
  namespace: mydomain-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 2Gi
