apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mydomain-dev
  name: n8n-secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["n8n-secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: n8n-secrets-reader-binding
  namespace: mydomain-dev
subjects:
- kind: ServiceAccount
  name: n8n-serviceaccount
  namespace: mydomain-dev
roleRef:
  kind: Role
  name: n8n-secrets-reader
  apiGroup: rbac.authorization.k8s.io
